# Generated by Django 4.1.5 on 2023-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.IntegerField()),
                ('var2', models.IntegerField()),
                ('var3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
