# Generated by Django 5.0 on 2024-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electriccar',
            name='battery_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gascar',
            name='fuel_efficiency',
            field=models.PositiveIntegerField(),
        ),
    ]
